name: Release Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Generate Version & Notes
        id: generate
        shell: pwsh
        run: |
          $date = Get-Date -Format 'yyyy.MM.dd'
          $build_num = $env:GITHUB_RUN_NUMBER -as [int]
          $build_num = $build_num % 100
          $build_ver = "$date.$build_num"
          Write-Output build_ver=$build_ver
          echo "release_ver=$build_ver" >> $env:GITHUB_OUTPUT

          [Console]::InputEncoding = [System.Text.Encoding]::UTF8
          [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
          $previous_tag = $(git describe --tags --abbrev=0 HEAD^ 2>$null)
          if ($previous_tag -ne '') {
            $previous_tag += '..HEAD'
          }
          $release_body = $(git log "$previous_tag" --pretty=format:"- [`%h`]($env:GITHUB_SERVER_URL/$env:GITHUB_REPOSITORY/commit/%H): %s")
          Write-Output previous_tag=$previous_tag
          Write-Output release_body=$release_body
          echo $release_body > CHANGELOG.txt

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Dotnet Build
        run: dotnet build -c Release -p:FileVersion="${{ steps.generate.outputs.release_ver }}" -p:AssemblyTitle="$env:GITHUB_SERVER_URL/$env:GITHUB_REPOSITORY"

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.generate.outputs.release_ver }}
          name: ${{ steps.generate.outputs.release_ver }}
          body_path: CHANGELOG.txt
          files: |
            ./bin/*/Release/*/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          